### PR TITLE
Enable secret scanning and actions for repos

### PR DESCRIPTION
**Pull request by netomi**
This is a first demo PR to illustrate the workflow to suggest changes.

If you approve, I will merge and apply the changes.

Related to https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3593

### CODE REVIEW

**Comment by netomi** [comment]
As you do not have workflows yet, the actions can be left disabled ofc.

**Review by fipro78 — APPROVED** [review]
I have to admit that I don't fully understand this. But I have trust in you and scanning for secrets is generally a good idea.

**Comment by netomi** [comment]
This file stores your current configuration of your GitHub organization and all contained repositories in a format called jsonnet. It takes some default values into account that we defined for all Eclipse projects. So technically the file stores the difference to the default.

You can see the full configuration in the generated page, e.g. for the nattable repository: https://eclipse-nattable.github.io/.eclipsefdn/repo-nattable/

In this PR I enable secret scanning and push protection as it was disabled when moving the repo. In general we advise our projects to enable that setting as it helps you detect and prevent that secrets are pushed to your repos, which will probably not happen but if it does its painful.

For the workflow settings. Currently workflows are disabled for your repos, so I took the freedom to enable it in case you want to add workflows, but if you do not plan to do so, I can also keep the setting as is.

**Comment by fipro78** [comment]
OK got it. Thanks for the explanation. :)

I will need some time to get familiar with all the GitHub settings and possibilities. 

If I want to enable discussions for the nattable repo, I need to add the `has_discussions` configuration to the jsonnet file and create a PR for it. Is that correct?

**Comment by netomi** [comment]
exactly. You can also define discussions on organization level, then you need to additionally specify a source repository where the discussons will be hosted.

You can find an example here: 

https://github.com/eclipse-orbit/.eclipsefdn/blob/main/otterdog/eclipse-orbit.jsonnet#L9-L11

btw. there is a page listing all Eclipse projects that have this self-service already enabled: https://eclipsefdn.github.io/otterdog-configs/

Some use it already quite extensively to have very consistent settings for all their repos.

**Comment by netomi** [comment]
changes have been applied.

**Pull request merged**
